os: linux
dist: bionic

language: python
python:
  - '3.7'
  - '3.8'

cache:
  pip: true

addons:
  apt:
    packages:
      - ffmpeg

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python -m compileall -f audiobot/ tests/ main.py
  - python -m flake8 --statistics audiobot/ tests/
  - python -m coverage run --source=audiobot -m unittest discover -vb tests/

after_success:
  - python -m coverage report -m
  - bash <(curl -s https://codecov.io/bash)
