os: "linux"
dist: "bionic"

language: "python"
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

cache:
  pip: "true"

addons:
  apt:
    packages:
      - "ffmpeg"

jobs:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"

install:
  - "pip install -r requirements.txt"
  - "pip install coverage"
  - "pip install flake8"

script:
  - "python -m compileall -f audiobot/"
  - "python -m flake8 --statistics audiobot/"
  - "python -m coverage run --source=audiobot -m unittest discover -vb tests/"

after_success:
  - "python -m coverage report -m"
  - "bash <(curl -s https://codecov.io/bash)"
