name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - run: pip install -r requirements.txt
      - run: pip install -r requirements-dev.txt
      - run: python -m compileall -f audiobot/ tests/ main.py
      - run: flake8 --statistics audiobot/ tests/
      - run: coverage run --source=audiobot -m unittest discover -vb tests/
      - run: coverage report -m

      - uses: codecov/codecov-action@v1
        with:
          verbose: true
